name: continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test (default)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
          cache: true
      # test project with default + extra features
      - run: cargo test --features image,ndarray,sop-class,rle,cli
      # test dicom-pixeldata with gdcm-rs
      - run: cargo test -p dicom-pixeldata --features gdcm
      # test dicom-pixeldata without default features
      - run: cargo test -p dicom-pixeldata --no-default-features
      # run Clippy with stable toolchain
      - if: matrix.rust == 'stable'
        run: cargo clippy
        env:
          RUSTFLAGS: -W warnings

  check_windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - run: cargo build --no-default-features --features=image,ndarray,sop-class,rle,cli,default_windows,inventory-registry

  check_macos:
    name: Check (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - run: cargo check
    